select * from customer limit 5;


--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue from customer 
group by 1 order by revenue asc;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as avg_rating from customer
group by 1 order by avg_rating desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,  round(avg(purchase_amount),2) as avg_amount from customer 
where shipping_type in ('Standard','Express')
group by 1;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, count(*) as customer_count, round(sum(purchase_amount),2) as total_revenue, round(avg(purchase_amount),2) as average_spend
from customer group by 1 order by 3,4 desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?


select item_purchased,
round(100.0*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by 1
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select * from customer;

select count(*) as customer_count,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_Segment
from customer
group by customer_Segment;

--Q8. What are the top 3 most purchased products within each category? 

with top_3_products as
(select category, item_purchased, count(*) as item_count,
dense_rank()over(partition by category order by count(*) desc)as rnk
from customer
group by 1,2)

select * from top_3_products where rnk<=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as customer_count from customer 
where previous_purchases > 5 group by 1;

--Q10. What is the revenue contribution of each age group? 


select age_group, sum(purchase_amount) as revenue_contribution
from customer group by 1 order by revenue_contribution desc;


